print("Tuple")
m=(3,5,2,1,7,8)
print("the value of tuple is:",m)
print("Now tuple and all its functions")
print("1.count(), using the count function we will count the number of occurrences of an element in the tuple")
print("the number of occurrences of 5 in",m,"is:",m.count(5))
print("2.index(), using the index function we will get the index of the first occurrence of an element in the tuple, remember that tuple index starts from 0")
print("the index of 7 in",m,"is:",m.index(7))

print("Notes:")
print("1. Tuples are immutable, which means we cannot change elements after creation")
print("2. Tuples can contain duplicate elements")
print("3. Tuples are ordered, so elements maintain their position")
print("4. Tuples can contain elements of different data types")
print("Example: m=(1,'hello',3.5,True)")
print("5. Tuples are generally more memory efficient and faster than lists for read-only operations")
print("Best practice: Use tuples when you need an immutable sequence of items, especially for fixed collections of data.")
print("Use lists when you need a mutable sequence that can be modified.")
print("Example of tuple unpacking:")
x, y, z, a, b, c = m
print("the values after unpacking the tuple are:",x,y,z,a,b,c)
