print("List vs Tuple vs Dictionary vs Set")
print("the List ")
a=[2,6,1,9,8,3]
print("the value of list is:",a)
print("Now list and all its functions")
print("1.append() , using this append function we will add a single element (not multiple arguments) to the end of the list")
a.append(9)
print("the value of list after the append is :",a)
print("2.extend() , using this extend function we will add elements from a single iterable (like a list, tuple, or set) to the end of the list")
a.extend([4,6]) 
print("the value of list after the extend is :",a)
print("3.insert() , using this insert function we will add an element at a specific index in the list,keep in mind that the list element starts with 0 index ")
a.insert(2, 5)
print("here the value of 5 is added at index 2 , which means the 5 is in 3 rd position in the list")
print("the value of list after the insert is :",a)
print("4.remove() , using the remove function we will remove the first occurence if we have duplicate elements in the list")
a.remove(9)
print("the value of list after the remove is :",a)
print("5.pop() , using the pop function we will remove the element at the specified index and its return value and if we dont specify the index it will remove the last element of the list")
print(a.pop())
print("the value of list after the pop is :",a)
print("6.enumerate(), using the enumerate function we will get the index and value of the list in the loop")
for index,value in enumerate(a):
    print("the index is:",index,"and the value is:",value)
print("7.sort(), using the sort function we will sort the list in ascending order by default")
a.sort()
print("the value of list after the sort is :",a)
print("8.reverse(), using the reverse function we will reverse the order of the list")
a.reverse()
print("the value of list after the reverse is :",a)
print("9.copy(), using the copy function we will create a shallow copy of the list")
b=a.copy()
print("the value of copied list from the list a is :",b)
print("10.count(), using the count function we will count the number of occurences of an element in the list")
the_occurences=a.count(3)
print("the number of occurences of 3 in the list is :",a,"is",the_occurences)
print("11.index(), using the index function we will get the index of the first occurence of an element in the list")
print("the index of first occurence of 6 in the list is :",a.index(6))
print("12.clear(),using the clear function we will remove all the elements from the list")
a.clear()
print("the function clear on the list is:",a)

print("Notes:")
print("1. the list is mutable which means we can change the element of the list after it is created")
print("2.the list can contain duplicate elements")
print("3.the list can be ordered or unordered")
print("4.the list can contain elements of different data types")
print("Example: a=[1,'hello',3.5,True]")



